# Delete these routes and define your own shop routes here

planetride_sylius_ai_audit_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: PlanetRide\SyliusAiAuditPlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

planetride_sylius_ai_audit_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: PlanetRide\SyliusAiAuditPlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
